name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # main 브랜치에 변경 사항이 있을 때 실행

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'true'  # Initialize and update submodules
          token: ${{ secrets.PAT_TOKEN }}  # Use the GitHub token for private repositories
      
      - name: Update submodules to latest commit
        run: git submodule update --remote

      # 2. Set up JDK 11
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      # 3. Build with Maven
      - name: Build with Maven
        run: mvn clean package

      # 4. Build Docker image
      - name: Build Docker image
        run: |
          docker build -t hd3ce/cookeat-server:latest .

      # 5. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 6. Push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push hd3ce/cookeat-server:latest

      # 7. Invoke Lambda function to deploy on EC2
      - name: Invoke Lambda for deployment
        run: |
          curl -X POST https://3gphc967el.execute-api.ap-northeast-2.amazonaws.com/default/cookeat-deploy-lambda \
          -H "x-api-key: ${{ secrets.X_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{}'
